// src/views/home/components/NewsList.vue
<template>
  <a-card
    class="news-box"
    :loading="loading"
    :bordered="false"
  >
    <div slot="title">新闻</div>
    <a
      slot="extra"
      href="/news/list"
    >更多</a>
    <div class="news-box-list">
      <div
        class="news-item"
        v-for="news in newsList"
        :key="news.id"
        @click="handleViewDetail(news.id)"
      >
        <div class="time-inner-box">
          <p>
            {{ news.month }}/{{ news.day }}
          </p>
          <div class="year-value">{{ news.year }}</div>
        </div>
        <div class="news-content-box">
          <div class="news-title-inner">{{ news.title }}</div>
          <p
            class="news-content-inner"
            v-html="news.description"
          >
          </p>
        </div>
      </div>
    </div>
  </a-card>
</template>

<script>
import { Ellipsis } from '@/components'
import { getNewsList } from '@/api/home'
export default {
  components: { Ellipsis },
  data() {
    return {
      loading: false,
      newsList: []
    }
  },
  mounted() {
    this.getNews()
  },
  methods: {
    getNews() {
      this.loading = true
      const req = { newsType: '1', pageSize: 3 }
      getNewsList(req).then((res) => {
        this.loading = false
        this.newsList = res.rows
      })
    },
    handleViewDetail(id) {
      this.$router.push('/news/detail/' + id)
    }
  }
}
</script>

<style>
@import './styles/news-list.less';
.news-content-inner {
  max-height: calc(18 * 2); /* 根据行数计算最大高度 */
  overflow: hidden;
}
</style>

// src/pages/home/components/news-list.tsx
import React from "react"
import "./styles/news-list.css"
import Paragraph from "antd/es/typography/Paragraph"
import { useNewsList } from "api/home"
import { News } from "types/home"
export const NewsListPart = (props: any) => {
  const { data: newsList } = useNewsList()
  return (
    <div className="news-box">
      <div className="news-box-list">
        {newsList?.map((v) => (
          <NewsItem key={v.id} news={v} />
        ))}
      </div>
    </div>
  )
}
export const NewsItem = ({ news }: { news: News }) => {
  return (
    <div className="news-item">
      <div className="time-inner-box">
        <p>
          {news.month}/{news.day}
        </p>
        <div className="year-value">{news.year}</div>
      </div>
      <div className="news-content-box">
        <div className="news-title-inner">{news.title}</div>
        <Paragraph className="news-content-inner" ellipsis={{ rows: 2 }}>
          {news.description}
        </Paragraph>
      </div>
    </div>
  )
}
