// src/pages/home/index.tsx
import React from "react"
import styled from "@emotion/styled"
import "./index.css"
import { ProductListPart } from "./components/product-list"
import { EntryProcessPart } from "./components/entry-process"
import { AccountListPart } from "./components/account-list"
import { NewsListPart } from "./components/news-list"
import { ServerDataNumPart } from "./components/serverData-num"
import { BannerPart } from "./components/banner"
export const HomePage = () => {
  return (
    <div className="home-page">
      <HomeHeaderNavBox
        className="home-header-nav-box"
        style={{
          textAlign: "center",
        }}
      >
        <BannerPart />
        <ServerDataNumPart />
      </HomeHeaderNavBox>
      <NoticeContainer>
        <AccountListPart />
        <NewsListPart />
      </NoticeContainer>
      <EntryProcessPart />
      <ProductListPart />
    </div>
  )
}
const HomeHeaderNavBox = styled.div`
  width: 100%;
  height: 320px;
  color: #fff;
  margin-bottom: 110px;
`
const NoticeContainer = styled.div`
  width: 1200px;
  margin: auto;
  display: flex;
  flex-direction: row;
  margin-bottom: 40px;
  gap: 10px;
`

// src/views/home/Index.vue
<template>
  <div class="home-page">
    <div class="home-header-nav-box">
      <BannerPart />
      <ServerDataNumPart />
    </div>
    <div class="notice-container">
      <AccountListPart />
      <NewsListPart />
    </div>
    <EntryProcessPart />
    <ProductListPart />
  </div>
</template>
<script>
import {
  BannerPart,
  ServerDataNumPart,
  AccountListPart,
  NewsListPart,
  EntryProcessPart,
  ProductListPart
} from '@/views/home/components'
export default {
  name: 'Home',
  components: {
    BannerPart,
    ServerDataNumPart,
    AccountListPart,
    NewsListPart,
    EntryProcessPart,
    ProductListPart
  }
}
</script>
<style lang="less" scoped>
.home-header-nav-box {
  position: relative;
  width: 100%;
  text-align: center;
  height: 320px;
  color: #fff;
  margin-bottom: 124px;
}
.notice-container {
  width: 1200px;
  margin: auto;
  display: flex;
  flex-direction: row;
  margin-bottom: 40px;
  gap: 10px;
}
</style>
